# -*- coding: utf-8 -*-
"""YouTube_video_downloader_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wpGE88-FMfHomEUp2exNnKYQWPzImKq0
"""

pip install pytube

import pytube

link = input('Paste the url here : ')

video = pytube.YouTube(link)

video.streams.first().download()

print("Downloaded Successfully, ",link)